### ISSUE TITLE
Can I make my AMI avalible for Spot instances

### ISSUE THREAD

**Issue by SolidRhino** [keithvassallomt/windows10-ec2#1]
When I try to create a Spot Instance, I get the following error:
`Spot instance requests are not supported for this AMI`

Is it possible to prepare a AMI for Spot Instance support?

Thank you

**Comment by keithvassallomt** [comment]
Hmmm, it should work.
Did you enable enhanced networking? Also make sure the AMI is in the region as the one you’re trying to create your SPOT request in. Then again, it’s entirely possible that AWS has stopped allowing SPOT for Windows BYOL

**Comment by SolidRhino** [comment]
If you mean ENA, yes. I tried to create the spot in the same region as the AMI.

**Comment by keithvassallomt** [comment]
Would you be willing to open a ticket with AWS? Honestly, this should work, unless you created a dedicated instance. I’ve really tried searching online but can’t find anything relevant, sorry!

**Comment by SolidRhino** [comment]
I tried to create a ticket with AWS, but technical support is not available under Basic Support Plan. So I'm stuck.

**Comment by SolidRhino** [comment]
Do you use Windows 10 or Windows 2019 server to play games? I ask this because you have 2 tutorials.

**Comment by keithvassallomt** [comment]
> Do you use Windows 10 or Windows 2019 server to play games? I ask this because you have 2 tutorials.

I normally use Server 2019. The Windows 10 tutorial is for people who specifically want Windows 10, or perhaps the odd game that doesn’t work on Server 2019

**Comment by UpperCenter** [comment]
+1 for the spot instance issue. I also get "Spot instance requests are not supported for this AMI." so I assume AWS doesn't support BYOL anymore.

**Comment by nitishtrivedi** [comment]
Hi Keith,

Might sound silly, but is there a way that you can share this AMI?
Can directly launch an instance using your AMI and g4dn.xlarge.

I saw your video on YouTube and its a brilliant job done there TBH

**Comment by keithvassallomt** [comment]
> Hi Keith,
> 
> Might sound silly, but is there a way that you can share this AMI? Can directly launch an instance using your AMI and g4dn.xlarge.
> 
> I saw your video on YouTube and its a brilliant job done there TBH

Unfortunately, the Microsoft EULA prevents the distribution of Microsoft Windows without a licence, even if its not activate it :( Otherwise I would gladly do so!

**Comment by nitishtrivedi** [comment]
Also, wanted to know, if this will work for Windows 11?
I have a license key but that is for Home edition. You have mentioned that it wont work for Home license.
Is there any workaround for the same?

**Comment by keithvassallomt** [comment]
> Also, wanted to know, if this will work for Windows 11? I have a license key but that is for Home edition. You have mentioned that it wont work for Home license. Is there any workaround for the same?

This will work for Windows 11, but only for the Pro (or higher) versions.
