### ISSUE TITLE
Get-S3Object : Specified value has invalid CRLF characters.

### ISSUE THREAD

**Issue by izzy667** [keithvassallomt/windows10-ec2#4]
```
Set-AWSCredential `
                 -AccessKey YOUR_ACCESS_KEY_HERE `
                 -SecretKey YOUR_SECRET_KEY_HERE `
                 -StoreAs default
```
Using that code for AWS credentials in some cases generates CRLF problem with http requests in shell.
I suggest to change it to one-liner without ` breaks.

**Comment by keithvassallomt** [comment]
Thanks for this! I've updated the guide accordingly.
